baseURL = "https://hexandcube.eu.org"
languageCode = "en-us"
title = "Hexandcube"
enableEmoji = true
# enableGitInfo = true
paginate = 18

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.hightempcolor]
    codeFences = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    tabWidth = 4


[params]
  version = "10.1-dev"
  description = "Nice to meet you, I'm hexandcube. I'm a hobby web developer from Poland."
  keywords = "Hexandcube, Wallpapers, Files, Windows, Desktop, Tools, Software, Webdev, translation"
  JsonLd = '''
  {
    "@context": "https://schema.org",
    "@type": "Person",
    "name": "Hexandcube",
    "email": "hexandcube@hexandcube.eu.org",
    "gender": "Male",
    "nationality": "Polish",
    "knowsLanguage": "Polish, English",
    "url": "https://hexandcube.eu.org",
    "image": "https://files.hexandcube.eu.org/images/avatar.png",
    "sameAs": [
      "https://github.com/hexandcube",
      "https://www.instagram.com/hexandcube/",
      "https://twitter.com/hexandcube",
      "https://mstdn.social/@hexandcube",
      "https://gitlab.com/hexandcube",
      "https://keybase.io/hexandcube",
      "https://www.youtube.com/c/hexandcube",
      "https://www.reddit.com/user/hexandcube",
      "https://unsplash.com/@hexandcube",
      "hhttps://500px.com/p/hexandcube",
      "https://addons.mozilla.org/en-US/firefox/user/14625252/"
    ]
  }
  '''

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = -100
    pre="fa-user"

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = -90
    pre="fa-newspaper"

  [[menu.main]]
    identifier = "files"
    name = "Files"
    url = "/files/"
    weight = -80
    pre="fa-cloud-arrow-down"
    
  [[menu.main]]
    identifier = "wallpapers"
    name = "Wallpapers"
    url = "/wallpapers/"
    weight = -70
    pre="fa-image"
    

